# config/_default/menus.toml

[[main]]
  name = "Resume"
  pageRef="resume"
  weight = 10

[[main]]
  name = "Projects"
  pageRef="projects"
  weight = 30

[[main]]
  name = "Contents"
  pageRef="contents"
  weight = 40
