colorScheme = "fire"
defaultAppearance = "dark" # valid options: light or dark
homepage.layout = "profile"
enableCodeCopy = true
enableSearch = true

[article]
  showDate = false
  showReadingTime = true

[header]
  layout = "hybrid"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[list]
  groupByYear = false

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true
